# Uncomment the next line to define a global platform for your project
 platform :ios, '13.2'

target 'Solocoin' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Solocoin
pod 'Firebase'
pod 'Firebase/Auth'
pod "FlagPhoneNumber", :git => 'https://github.com/ecomparer/FlagPhoneNumber.git'
pod 'SkyFloatingLabelTextField'
pod 'IQKeyboardManagerSwift'
pod 'SDWebImage'
end
